/** Canonical CoinGecko ID → Binance USDT pair mapping shared by all providers. */
export const COINGECKO_TO_BINANCE: Record<string, string> = {
  'bitcoin': 'BTCUSDT',
  'ethereum': 'ETHUSDT',
  'solana': 'SOLUSDT',
  'binancecoin': 'BNBUSDT',
  'ripple': 'XRPUSDT',
  'dogecoin': 'DOGEUSDT',
  'cardano': 'ADAUSDT',
  'avalanche-2': 'AVAXUSDT',
  'chainlink': 'LINKUSDT',
  'sui': 'SUIUSDT',
  'polkadot': 'DOTUSDT',
  'shiba-inu': 'SHIBUSDT',
  'tron': 'TRXUSDT',
  'litecoin': 'LTCUSDT',
  'matic-network': 'MATICUSDT',
  'internet-computer': 'ICPUSDT',
  'bitcoin-cash': 'BCHUSDT',
  'near': 'NEARUSDT',
  'uniswap': 'UNIUSDT',
  'aptos': 'APTUSDT',
  'stellar': 'XLMUSDT',
  'monero': 'XMRUSDT',
  'ethereum-classic': 'ETCUSDT',
  'cosmos': 'ATOMUSDT',
  'filecoin': 'FILUSDT',
  'hedera-hashgraph': 'HBARUSDT',
  'arbitrum': 'ARBUSDT',
  'optimism': 'OPUSDT',
  'injective-protocol': 'INJUSDT',
  'sei-network': 'SEIUSDT',
  'the-graph': 'GRTUSDT',
  'fetch-ai': 'FETUSDT',
  'render-token': 'RENDERUSDT',
  'algorand': 'ALGOUSDT',
  'sandbox': 'SANDUSDT',
  'decentraland': 'MANAUSDT',
  'axie-infinity': 'AXSUSDT',
  'flow': 'FLOWUSDT',
  'immutable-x': 'IMXUSDT',
  'pepe': 'PEPEUSDT',
  'floki': 'FLOKIUSDT',
  'dogwifcoin': 'WIFUSDT',
  'kaspa': 'KASUSDT',
  'thorchain': 'RUNEUSDT',
  'pendle': 'PENDLEUSDT',
  'toncoin': 'TONUSDT',
  'notcoin': 'NOTUSDT',
  'ethena': 'ENAUSDT',
  'starknet': 'STRKUSDT',
  'dydx-chain': 'DYDXUSDT',
  'aave': 'AAVEUSDT',
  'maker': 'MKRUSDT',
  'curve-dao-token': 'CRVUSDT',
  'fantom': 'FTMUSDT',
  'eos': 'EOSUSDT',
  'vechain': 'VETUSDT',
  'theta-token': 'THETAUSDT',
  'gala': 'GALAUSDT',
  'worldcoin-wld': 'WLDUSDT',
  'celestia': 'TIAUSDT',
  'pyth-network': 'PYTHUSDT',
  'jupiter-exchange-solana': 'JUPUSDT',
  'bonk': 'BONKUSDT',
  'ondo-finance': 'ONDOUSDT',
  'eigenlayer': 'EIGENUSDT',
  // CoinMarketCap slug variants
  'bnb': 'BNBUSDT',
  'xrp': 'XRPUSDT',
  'doge': 'DOGEUSDT',
  'ada': 'ADAUSDT',
  'avax': 'AVAXUSDT',
  'link': 'LINKUSDT',
  'dot': 'DOTUSDT',
  'shib': 'SHIBUSDT',
  'trx': 'TRXUSDT',
  'ltc': 'LTCUSDT',
  'pol': 'MATICUSDT',
  'icp': 'ICPUSDT',
  'bch': 'BCHUSDT',
  'uni': 'UNIUSDT',
  'apt': 'APTUSDT',
  'xlm': 'XLMUSDT',
  'xmr': 'XMRUSDT',
  'etc': 'ETCUSDT',
  'atom': 'ATOMUSDT',
  'fil': 'FILUSDT',
  'hbar': 'HBARUSDT',
  'arb': 'ARBUSDT',
  'op': 'OPUSDT',
  'inj': 'INJUSDT',
  'sei': 'SEIUSDT',
  'grt': 'GRTUSDT',
  'fet': 'FETUSDT',
  'render': 'RENDERUSDT',
  'algo': 'ALGOUSDT',
  'sand': 'SANDUSDT',
  'mana': 'MANAUSDT',
  'axs': 'AXSUSDT',
  'imx': 'IMXUSDT',
  'kas': 'KASUSDT',
  'rune': 'RUNEUSDT',
  'ton': 'TONUSDT',
  'not': 'NOTUSDT',
  'ena': 'ENAUSDT',
  'strk': 'STRKUSDT',
  'dydx': 'DYDXUSDT',
  'crv': 'CRVUSDT',
  'ftm': 'FTMUSDT',
  'vet': 'VETUSDT',
  'theta': 'THETAUSDT',
  'wld': 'WLDUSDT',
  'tia': 'TIAUSDT',
  'pyth': 'PYTHUSDT',
  'jup': 'JUPUSDT',
  'ondo': 'ONDOUSDT',
};

/**
 * Resolve a Binance USDT symbol from a canonical coin ID.
 * Falls back to `${upperSymbol}USDT` when not in the map.
 */
export function resolveBinanceSymbol(coinId: string, fallbackSymbol: string): string {
  const key = coinId.toLowerCase();
  return COINGECKO_TO_BINANCE[key] ?? `${fallbackSymbol.toUpperCase()}USDT`;
}
